import React from "react";
import { useI18n } from "./i18n.js";
import "./planned-goal.css";
import type { PlannedDraft } from "./planned-goal-form.js";
export function PlannedGoalEditor({ value: d, onChange }: { value: PlannedDraft; onChange: (v: PlannedDraft) => void }) {
  const { tr } = useI18n();
  const set = <K extends keyof PlannedDraft>(key: K, v: PlannedDraft[K]) => onChange({ ...d, [key]: v });
  const phaseSet = (i: number, field: string, value: unknown) => set("phases", d.phases.map((p, j) => j === i ? { ...p, [field]: value } : p));
  return <fieldset className="plannedEditor automationFieldWide"><legend>{tr("Plan settings", "计划设置")}</legend>
    <label className="plannedToggle"><input type="checkbox" checked={d.enabled} onChange={e => set("enabled", e.target.checked)} />{tr("Customize phases, priorities and quality checks", "自定义阶段、优先级与质量检查")}</label>
    {!d.enabled && <p>{tr("The executor plans from your objective. Progress, plan revisions and checkpoints are always saved within the time budget above.", "执行器根据目标规划；进度、计划版本和检查点始终会在上述时间预算内保存。")}</p>}
    {d.enabled && <>
      <p>{tr("Saved command slices can continue after the chat turn ends. New judgment waits for the selected controller; normal Chat is not guaranteed to wake itself.", "聊天轮次结束后，已保存的命令步骤可以继续。新的判断等待所选控制器；普通 Chat 不保证能自动唤醒自己。")}</p>
      <div className="plannedFields"><label><span>{tr("Planning mode", "规划方式")}</span><select value={d.mode} onChange={e => set("mode", e.target.value as PlannedDraft["mode"])}><option value="fixed">{tr("Fixed phases", "固定阶段")}</option><option value="guided">{tr("Guided by priorities", "按优先级规划")}</option><option value="autonomous">{tr("Plan from the goal", "从目标自主规划")}</option></select></label>
        <label><span>{tr("Minimum useful time (minutes)", "最少有效工作时间（分钟）")}</span><input type="number" min="1" value={d.minMinutes} onChange={e => set("minMinutes", e.target.value)} /></label>
        <label><span>{tr("Maximum time (minutes)", "最长时间（分钟）")}</span><input type="number" min="1" value={d.maxMinutes} onChange={e => set("maxMinutes", e.target.value)} /></label>
        <label><span>{tr("Stop at (your local time)", "停止时间（你的本地时间）")}</span><input type="datetime-local" value={d.endAt} onChange={e => set("endAt", e.target.value)} /></label>
        <label><span>{tr("Finalization reserve (minutes)", "预留收尾时间（分钟）")}</span><input type="number" min="0" value={d.reserveMinutes} onChange={e => set("reserveMinutes", e.target.value)} /></label>
      </div>
      <small>{tr("The earliest limit wins. Minimum time never requires filler edits. Reserve time for final checks and a factual report.", "最早的限制生效。最少时间不会要求凑数修改。预留时间用于最终检查与事实报告。")}</small>
      <label className="plannedWide"><span>{tr("Priorities (one per line)", "优先级（每行一项）")}</span><textarea rows={3} value={d.priorities} maxLength={12000} onChange={e => set("priorities", e.target.value)} /></label>
      <div className="plannedPhases"><h3>{tr("Phases", "阶段")}</h3>{d.phases.map((p, i) => <fieldset key={p.id}><legend>{tr("Phase", "阶段")} {i + 1}</legend>
        <label><span>{tr("Objective", "目标")}</span><input value={p.objective} maxLength={2000} onChange={e => phaseSet(i, "objective", e.target.value)} /></label>
        <label><span>{tr("Success criteria", "成功标准")}</span><textarea rows={2} value={p.criteria} maxLength={2000} onChange={e => phaseSet(i, "criteria", e.target.value)} /></label>
        <div className="plannedFields"><label><span>{tr("Minimum minutes", "最少分钟")}</span><input type="number" min="1" value={p.minMinutes} onChange={e => phaseSet(i, "minMinutes", e.target.value)} /></label><label><span>{tr("Maximum minutes", "最多分钟")}</span><input type="number" min="1" value={p.maxMinutes} onChange={e => phaseSet(i, "maxMinutes", e.target.value)} /></label></div>
        <label><span>{tr("Verification command (optional)", "验证命令（可选）")}</span><textarea rows={2} value={p.verify} maxLength={4000} onChange={e => phaseSet(i, "verify", e.target.value)} /></label>
        <label><span>{tr("Authorized deterministic command (optional)", "已授权的确定性命令（可选）")}</span><textarea rows={2} value={p.command} maxLength={4000} onChange={e => phaseSet(i, "command", e.target.value)} /></label>
        {i > 0 && <div className="plannedDependencies"><span>{tr("Requires completed phases", "必须完成的前置阶段")}</span>{d.phases.slice(0, i).map(prior => <label key={prior.id}><input type="checkbox" checked={p.dependsOn.includes(prior.id)} onChange={e => phaseSet(i, "dependsOn", e.target.checked ? [...p.dependsOn, prior.id] : p.dependsOn.filter(x => x !== prior.id))} />{prior.objective || prior.id}</label>)}</div>}
        <button type="button" className="ghostButton" onClick={() => set("phases", d.phases.filter(x => x.id !== p.id).map(x => ({ ...x, dependsOn: x.dependsOn.filter(id => id !== p.id) })))}>{tr("Remove phase", "删除阶段")}</button>
      </fieldset>)}<button type="button" className="ghostButton" disabled={d.phases.length >= 24} onClick={() => set("phases", [...d.phases, { id: "phase-" + crypto.randomUUID().slice(0, 8), objective: "", criteria: "", verify: "", minMinutes: "", maxMinutes: "", dependsOn: [], command: "" }])}>+ {tr("Add phase", "添加阶段")}</button></div>
      <label className="plannedToggle"><input type="checkbox" checked={d.quality} onChange={e => set("quality", e.target.checked)} />{tr("Promote only after required checks pass", "必需检查通过后才接受修改")}</label>
      {d.quality && <div className="plannedQuality"><p>{tr("Requires a clean Git repository root and updated remotelink. Work stays in a task-owned detached worktree. Rejected attempts are preserved; accepted checkpoints are not automatically applied to your original branch.", "需要干净的 Git 仓库根目录和新版 remotelink。工作在任务拥有的独立 worktree 中进行，失败尝试会保留，已验收版本不会自动应用到原分支。")}</p>{d.checks.map((c, i) => <div className="plannedCheck" key={i}><label><span>{tr("Check name", "检查名称")}</span><input value={c.name} maxLength={80} onChange={e => set("checks", d.checks.map((x, j) => j === i ? { ...x, name: e.target.value } : x))} /></label><label><span>{tr("Command", "命令")}</span><textarea rows={2} value={c.command} maxLength={4000} onChange={e => set("checks", d.checks.map((x, j) => j === i ? { ...x, command: e.target.value } : x))} /></label><button type="button" className="ghostButton" disabled={d.checks.length === 1} onClick={() => set("checks", d.checks.filter((_, j) => j !== i))}>{tr("Remove", "删除")}</button></div>)}<button type="button" className="ghostButton" disabled={d.checks.length >= 8} onClick={() => set("checks", [...d.checks, { name: "", command: "" }])}>+ {tr("Add check", "添加检查")}</button></div>}
      <label className="plannedToggle"><input type="checkbox" checked={d.continueWork} onChange={e => set("continueWork", e.target.checked)} />{tr("Look for valuable safe work after planned priorities settle", "计划优先级处理后寻找有价值的安全工作")}</label>
      <div className="plannedFields"><label><span>{tr("Same failure limit", "重复失败上限")}</span><input type="number" min="1" max="20" value={d.sameFailure} onChange={e => set("sameFailure", e.target.value)} /></label><label><span>{tr("No-progress turn limit", "无进展轮次上限")}</span><input type="number" min="1" max="100" value={d.noProgress} onChange={e => set("noProgress", e.target.value)} /></label><label><span>{tr("Strategy retry limit", "策略重试上限")}</span><input type="number" min="0" max="10" value={d.retries} onChange={e => set("retries", e.target.value)} /></label></div>
    </>}
  </fieldset>;
}
type Result = { id: string; outcome: string; spent_seconds: number; evidence: string; blocker?: string; remaining_work: string; checkpoint?: string };
export type PlannedProgress = { active_phase?: string; started_at: string; finished_at?: string; finalizing?: boolean; needs_reasoning?: string; plan: { phases: { id: string; objective: string }[]; time_policy: { max_duration_seconds?: number; end_at?: string } }; outcomes: Result[]; green_frontier?: { checkpoint: string; at: string }; candidate?: { status: string; evidence?: string; path?: string }; checks: { name: string; passed: boolean; exit_code: number | null; evidence: string }[]; rejected: { evidence: string; path?: string }[]; workspace?: { path: string }; report?: unknown };
export function PlannedGoalProgress({ value: p, expiresAt }: { value: PlannedProgress; expiresAt: string | null }) {
  const { tr, locale } = useI18n();
  const bounds = [p.plan.time_policy.end_at, expiresAt, p.plan.time_policy.max_duration_seconds ? new Date(Date.parse(p.started_at) + p.plan.time_policy.max_duration_seconds * 1000).toISOString() : undefined].filter(Boolean) as string[];
  const deadline = bounds.length ? new Date(Math.min(...bounds.map(Date.parse))) : null;
  const active = p.plan.phases.find(x => x.id === p.active_phase);
  const outcome = (s: string) => ({ completed: tr("Accepted", "已接受"), partial: tr("Partial", "部分完成"), blocked: tr("Blocked", "阻塞"), failed: tr("Failed", "失败"), skipped: tr("Skipped", "跳过") }[s] || s);
  return <section className="plannedProgress"><h3>{p.finished_at ? tr("Finalized · inspect the outcome", "已收尾 · 请查看实际成果") : p.needs_reasoning ? tr("Source reasoning needed", "需要源 AI 判断") : p.finalizing ? tr("Finalizing", "正在收尾") : tr("Plan progress", "计划进度")}</h3>
    <div className="plannedSummary"><div><span>{tr("Current phase", "当前阶段")}</span><strong>{active?.objective || tr("No active phase", "暂无活动阶段")}</strong></div><div><span>{tr("Accepted phases", "已接受阶段")}</span><strong>{p.outcomes.filter(x => x.outcome === "completed").length} / {p.plan.phases.length}</strong></div><div><span>{tr("Elapsed", "已用时间")}</span><strong>{Math.max(0, Math.floor(((p.finished_at ? Date.parse(p.finished_at) : Date.now()) - Date.parse(p.started_at)) / 60000))} {tr("min", "分钟")}</strong></div><div><span>{tr("Deadline", "停止期限")}</span><strong>{deadline?.toLocaleString(locale === "zh" ? "zh-CN" : "en-US") || tr("Task expiry applies", "遵循任务到期时间")}</strong></div></div>
    {p.needs_reasoning && <p className="plannedReason">{p.needs_reasoning}</p>}
    <p><strong>{tr("Accepted checkpoint", "已验收版本")}: </strong><code>{p.green_frontier?.checkpoint || tr("No verified baseline yet", "尚无已验证基线")}</code></p>
    {p.candidate && <p><strong>{tr("Candidate", "候选修改")}: </strong>{({ working: tr("In progress", "进行中"), evaluating: tr("Checking", "检查中"), accepted: tr("Accepted", "已接受"), rejected: tr("Rejected; frontier retained", "已拒绝，保留已验收版本"), unknown: tr("Outcome unknown; inspection needed", "结果未知，需要检查") }[p.candidate.status] || p.candidate.status)}{p.candidate.evidence && <span className="plannedEvidence">{p.candidate.evidence}</span>}</p>}
    {p.workspace && <p className="plannedWorkspace">{tr("Task worktree", "任务 worktree")}: <code>{p.workspace.path}</code><br />{tr("Accepted work requires review before applying it to your original branch.", "将成果应用到原分支前，需要先审查。")}</p>}
    {!!p.checks.length && <div className="plannedChecks"><h4>{tr("Latest quality results", "最近质量检查")}</h4>{p.checks.map((c, i) => <details key={i}><summary><strong>{c.name}</strong><span>{c.passed ? tr("Passed", "通过") : tr("Not passed", "未通过")} · {tr("Exit", "退出码")} {c.exit_code ?? "—"}</span></summary><pre>{c.evidence}</pre></details>)}</div>}
    <div className="plannedHistory"><h4>{tr("Phase outcomes", "阶段结果")}</h4>{p.plan.phases.map(phase => { const r = p.outcomes.find(x => x.id === phase.id); return <details key={phase.id}><summary><strong>{phase.objective}</strong><span>{r ? outcome(r.outcome) : phase.id === p.active_phase ? tr("Active", "活动") : tr("Untouched", "未处理")}</span></summary>{r && <><p>{r.evidence}</p>{r.blocker && <p>{tr("Blocker", "阻塞")}: {r.blocker}</p>}{r.remaining_work && <p>{tr("Remaining", "剩余工作")}: {r.remaining_work}</p>}<p>{Math.round(r.spent_seconds / 60)} {tr("min", "分钟")}{r.checkpoint && <> · <code>{r.checkpoint}</code></>}</p></>}</details>; })}</div>
    {!!p.rejected.length && <details><summary>{tr("Rejected attempts", "未接受的尝试")} ({p.rejected.length})</summary>{p.rejected.map((r, i) => <div key={i}><p>{r.evidence}</p>{r.path && <code>{r.path}</code>}</div>)}</details>}
  </section>;
}
