changelog:
  exclude:
    labels:
      - ignore-for-release
      - skip-changelog
    authors:
      - dependabot

  categories:
    - title: Features
      labels:
        - enhancement
        - feature
    - title: Fixes
      labels:
        - bug
        - fix
    - title: Security
      labels:
        - security
    - title: Documentation
      labels:
        - documentation
    - title: Other changes
      labels:
        - "*"
