import assert from "node:assert/strict";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { goalWorkspace } from "../src/goal-workspace.js";
import { assertCommandAllowed, RemoteArcExecutionCore } from "@remotearc/execution-core";
const exec = promisify(execFile);
const root = await fs.mkdtemp(path.join(os.tmpdir(), "remote-arc-worktree-test-"));
const git = async (...args: string[]) => (await exec("git", ["-C", root, ...args], { windowsHide: true, env: { ...process.env, GIT_CONFIG_NOSYSTEM: "1" } })).stdout.trim();
try {
  await git("init"); await git("config", "core.autocrlf", "false"); await fs.writeFile(path.join(root, "app.txt"), "baseline\n");
  await git("add", "."); await git("-c", "user.name=Test", "-c", "user.email=test@test.invalid", "-c", "commit.gpgSign=false", "commit", "-m", "baseline");
  const originalHead = await git("rev-parse", "HEAD");
  const policy = { workspaceRoots: [root], protectSensitivePaths: true };
  const call = (action: string, op: string, extra = {}) => goalWorkspace({ task_id: "test-task", workspace: root, action, operation_id: op, ...extra }, policy) as Promise<{ path: string; frontier: string; generation: number; tree?: string }>;
  const first = await call("create", "create"); assert.equal(first.frontier, originalHead);
  const duplicate = await call("create", "create"); assert.equal(duplicate.path, first.path);
  await fs.writeFile(path.join(first.path, "app.txt"), "accepted candidate\n");
  const fingerprint = await call("fingerprint", "fingerprint");
  const accepted = await call("capture", "capture", { expected_frontier: first.frontier, expected_tree: fingerprint.tree });
  assert.notEqual(accepted.frontier, originalHead); assert.equal(await git("rev-parse", "HEAD"), originalHead);
  assert.equal(await fs.readFile(path.join(root, "app.txt"), "utf8"), "baseline\n");
  assert.equal((await call("capture", "capture", { expected_frontier: first.frontier, expected_tree: fingerprint.tree })).frontier, accepted.frontier);
  await fs.writeFile(path.join(first.path, "app.txt"), "regression\n");
  const rejected = await call("reject", "reject", { expected_frontier: accepted.frontier });
  assert.notEqual(rejected.path, first.path); assert.equal(rejected.frontier, accepted.frontier);
  assert.equal(await fs.readFile(path.join(first.path, "app.txt"), "utf8"), "regression\n");
  assert.equal(await fs.readFile(path.join(rejected.path, "app.txt"), "utf8"), "accepted candidate\n");
  await fs.writeFile(path.join(root, "user-work.txt"), "preserve user work\n");
  await assert.rejects(goalWorkspace({ task_id: "other-task", workspace: root, action: "create", operation_id: "create" }, policy), /clean checkout/);
  const checked = await call("fingerprint", "check-race");
  await fs.writeFile(path.join(rejected.path, "app.txt"), "concurrent user change\n");
  await assert.rejects(call("capture", "race-capture", { expected_frontier: rejected.frontier, expected_tree: checked.tree }), /changed during validation/);
  assert.equal(await fs.readFile(path.join(root, "user-work.txt"), "utf8"), "preserve user work\n");
  await assert.rejects(goalWorkspace({ task_id: "test-task", workspace: root, action: "create", operation_id: "outside" }, { workspaceRoots: [path.join(root, "app.txt")] }), /Blocked|outside|scope/i);
  assert.throws(() => assertCommandAllowed("shutdown /s /t 0"), { message: "Blocked by Remote Arc Safety Guard: system shutdown or reboot. Run this action manually on the device if you intentionally need it." });
  const core = new RemoteArcExecutionCore("full");
  await fs.mkdir(path.join(root, "user-folder"));
  await fs.symlink(path.join(root, "user-folder"), path.join(rejected.path, "escape"), process.platform === "win32" ? "junction" : "dir");
  await assert.rejects(core.callTool("write_file", { path: path.join(rejected.path, "escape", "must-not-write.txt"), content: "blocked" }, { ...policy, taskWorkspaceRoot: rejected.path }), /Task Workspace/);
  const command = '"' + process.execPath + '" -e "setTimeout(()=>{},30000)"';
  const result = await core.callTool("start_process", { command, cwd: root, background: true, max_duration_seconds: 1 }, policy);
  const processId = JSON.parse(result.content[0]!.text).process_id;
  await new Promise(resolve => setTimeout(resolve, 1800));
  const status = JSON.parse((await core.callTool("process_status", { process_id: processId }, policy)).content[0]!.text);
  assert.equal(status.status, "exited"); assert.notEqual(status.exit_code, 0);
  console.log("PASS: real owned worktrees, checkpoint idempotency, reject isolation, unchanged user branch/files, concurrent-change fence, exact guard and process deadline");
} finally {
  const resolved = path.resolve(root);
  if (path.dirname(resolved) !== path.resolve(os.tmpdir()) || !path.basename(resolved).startsWith("remote-arc-worktree-test-")) throw new Error("Invalid cleanup target");
  await fs.rm(resolved, { recursive: true, force: true });
}
